// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace TransactionProcessor.Mobile.UITests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("LogoutLoginMerchantDetails")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    [global::NUnit.Framework.CategoryAttribute("background")]
    [global::NUnit.Framework.CategoryAttribute("login")]
    [global::NUnit.Framework.CategoryAttribute("toolbar")]
    [global::NUnit.Framework.CategoryAttribute("profile")]
    [global::NUnit.Framework.CategoryAttribute("base")]
    [global::NUnit.Framework.CategoryAttribute("sharedapp")]
    [global::NUnit.Framework.CategoryAttribute("shared")]
    public partial class LogoutLoginMerchantDetailsFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "background",
                "login",
                "toolbar",
                "profile",
                "base",
                "sharedapp",
                "shared"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "LogoutLoginMerchantDetails", null, global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "LogoutLoginMerchantDetails.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 4
#line hidden
            global::Reqnroll.Table table25 = new global::Reqnroll.Table(new string[] {
                        "Role Name"});
            table25.AddRow(new string[] {
                        "Merchant"});
#line 6
 await testRunner.GivenAsync("the following security roles exist", ((string)(null)), table25, "Given ");
#line hidden
            global::Reqnroll.Table table26 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Description"});
            table26.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST  Scope",
                        "A scope for Transaction Processor REST"});
            table26.AddRow(new string[] {
                        "transactionProcessorACL",
                        "Transaction Processor ACL REST  Scope",
                        "A scope for Transaction Processor ACL REST"});
#line 10
 await testRunner.GivenAsync("I create the following api scopes", ((string)(null)), table26, "Given ");
#line hidden
            global::Reqnroll.Table table27 = new global::Reqnroll.Table(new string[] {
                        "Name",
                        "DisplayName",
                        "Secret",
                        "Scopes",
                        "UserClaims"});
            table27.AddRow(new string[] {
                        "transactionProcessor",
                        "Transaction Processor REST",
                        "Secret1",
                        "transactionProcessor",
                        "merchantId, estateId, role"});
            table27.AddRow(new string[] {
                        "transactionProcessorACL",
                        "Transaction Processor ACL REST",
                        "Secret1",
                        "transactionProcessorACL",
                        "merchantId, estateId, role"});
#line 15
 await testRunner.GivenAsync("the following api resources exist", ((string)(null)), table27, "Given ");
#line hidden
            global::Reqnroll.Table table28 = new global::Reqnroll.Table(new string[] {
                        "ClientId",
                        "ClientName",
                        "Secret",
                        "Scopes",
                        "GrantTypes"});
            table28.AddRow(new string[] {
                        "serviceClient",
                        "Service Client",
                        "Secret1",
                        "transactionProcessor,transactionProcessorACL",
                        "client_credentials"});
            table28.AddRow(new string[] {
                        "mobileAppClient",
                        "Mobile App Client",
                        "Secret1",
                        "transactionProcessorACL,transactionProcessor",
                        "password"});
#line 20
 await testRunner.GivenAsync("the following clients exist", ((string)(null)), table28, "Given ");
#line hidden
            global::Reqnroll.Table table29 = new global::Reqnroll.Table(new string[] {
                        "ClientId"});
            table29.AddRow(new string[] {
                        "serviceClient"});
#line 25
 await testRunner.GivenAsync("I have a token to access the estate management and transaction processor acl reso" +
                    "urces", ((string)(null)), table29, "Given ");
#line hidden
            global::Reqnroll.Table table30 = new global::Reqnroll.Table(new string[] {
                        "EstateName"});
            table30.AddRow(new string[] {
                        "Test Estate 1"});
#line 29
 await testRunner.GivenAsync("I have created the following estates", ((string)(null)), table30, "Given ");
#line hidden
            global::Reqnroll.Table table31 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "RequireCustomMerchantNumber",
                        "RequireCustomTerminalNumber"});
            table31.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "True",
                        "True"});
            table31.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher",
                        "True",
                        "True"});
            table31.AddRow(new string[] {
                        "Test Estate 1",
                        "PataPawa PostPay",
                        "True",
                        "True"});
            table31.AddRow(new string[] {
                        "Test Estate 1",
                        "PataPawa PrePay",
                        "True",
                        "True"});
#line 33
 await testRunner.GivenAsync("I have created the following operators", ((string)(null)), table31, "Given ");
#line hidden
            global::Reqnroll.Table table32 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName"});
            table32.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom"});
            table32.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher"});
            table32.AddRow(new string[] {
                        "Test Estate 1",
                        "PataPawa PostPay"});
            table32.AddRow(new string[] {
                        "Test Estate 1",
                        "PataPawa PrePay"});
#line 40
 await testRunner.AndAsync("I have assigned the following operators to the estates", ((string)(null)), table32, "And ");
#line hidden
            global::Reqnroll.Table table33 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription"});
            table33.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "Safaricom Contract"});
            table33.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher",
                        "Hospital 1 Contract"});
            table33.AddRow(new string[] {
                        "Test Estate 1",
                        "PataPawa PostPay",
                        "PataPawa PostPay Contract"});
            table33.AddRow(new string[] {
                        "Test Estate 1",
                        "PataPawa PrePay",
                        "PataPawa PrePay Contract"});
#line 47
 await testRunner.GivenAsync("I create a contract with the following values", ((string)(null)), table33, "Given ");
#line hidden
            global::Reqnroll.Table table34 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "OperatorName",
                        "ContractDescription",
                        "ProductName",
                        "DisplayText",
                        "Value",
                        "ProductType"});
            table34.AddRow(new string[] {
                        "Test Estate 1",
                        "Safaricom",
                        "Safaricom Contract",
                        "Variable Topup",
                        "Custom",
                        "",
                        "MobileTopup"});
            table34.AddRow(new string[] {
                        "Test Estate 1",
                        "Voucher",
                        "Hospital 1 Contract",
                        "10 KES",
                        "10 KES",
                        "10.00",
                        "Voucher"});
            table34.AddRow(new string[] {
                        "Test Estate 1",
                        "PataPawa PostPay",
                        "PataPawa PostPay Contract",
                        "Post Pay Bill Pay",
                        "Bill Pay (Post)",
                        "",
                        "BillPayment"});
            table34.AddRow(new string[] {
                        "Test Estate 1",
                        "PataPawa PrePay",
                        "PataPawa PrePay Contract",
                        "Pre Pay Bill Pay",
                        "Bill Pay (Pre)",
                        "",
                        "BillPayment"});
#line 54
 await testRunner.WhenAsync("I create the following Products", ((string)(null)), table34, "When ");
#line hidden
            global::Reqnroll.Table table35 = new global::Reqnroll.Table(new string[] {
                        "MerchantName",
                        "AddressLine1",
                        "AddressLine2",
                        "AddressLine3",
                        "AddressLine4",
                        "Town",
                        "Region",
                        "PostalCode",
                        "Country",
                        "ContactName",
                        "EmailAddress",
                        "EstateName"});
            table35.AddRow(new string[] {
                        "Test Merchant 1",
                        "test address line 1",
                        "test address line 2",
                        "test address line 3",
                        "test address line 4",
                        "TestTown",
                        "Test Region",
                        "TE57 1NG",
                        "United Kingdom",
                        "Test Contact 1",
                        "testcontact1@merchant1.co.uk",
                        "Test Estate 1"});
            table35.AddRow(new string[] {
                        "Test Merchant 2",
                        "test address line 1",
                        "test address line 2",
                        "test address line 3",
                        "test address line 4",
                        "TestTown",
                        "Test Region",
                        "TE57 1NG",
                        "United Kingdom",
                        "Test Contact 2",
                        "testcontact2@merchant2.co.uk",
                        "Test Estate 1"});
#line 61
 await testRunner.GivenAsync("I create the following merchants", ((string)(null)), table35, "Given ");
#line hidden
            global::Reqnroll.Table table36 = new global::Reqnroll.Table(new string[] {
                        "OperatorName",
                        "MerchantName",
                        "MerchantNumber",
                        "TerminalNumber",
                        "EstateName"});
            table36.AddRow(new string[] {
                        "Safaricom",
                        "Test Merchant 1",
                        "00000001",
                        "10000001",
                        "Test Estate 1"});
            table36.AddRow(new string[] {
                        "Voucher",
                        "Test Merchant 1",
                        "00000001",
                        "10000001",
                        "Test Estate 1"});
            table36.AddRow(new string[] {
                        "PataPawa PostPay",
                        "Test Merchant 1",
                        "00000001",
                        "10000001",
                        "Test Estate 1"});
            table36.AddRow(new string[] {
                        "PataPawa PrePay",
                        "Test Merchant 1",
                        "00000001",
                        "10000001",
                        "Test Estate 1"});
            table36.AddRow(new string[] {
                        "Safaricom",
                        "Test Merchant 2",
                        "00000002",
                        "10000002",
                        "Test Estate 1"});
            table36.AddRow(new string[] {
                        "Voucher",
                        "Test Merchant 2",
                        "00000002",
                        "10000002",
                        "Test Estate 1"});
            table36.AddRow(new string[] {
                        "PataPawa PostPay",
                        "Test Merchant 2",
                        "00000002",
                        "10000002",
                        "Test Estate 1"});
            table36.AddRow(new string[] {
                        "PataPawa PrePay",
                        "Test Merchant 2",
                        "00000002",
                        "10000002",
                        "Test Estate 1"});
#line 66
 await testRunner.GivenAsync("I have assigned the following  operator to the merchants", ((string)(null)), table36, "Given ");
#line hidden
            global::Reqnroll.Table table37 = new global::Reqnroll.Table(new string[] {
                        "MerchantName",
                        "EstateName"});
            table37.AddRow(new string[] {
                        "Test Merchant 1",
                        "Test Estate 1"});
            table37.AddRow(new string[] {
                        "Test Merchant 2",
                        "Test Estate 1"});
#line 77
 await testRunner.GivenAsync("I have assigned the following devices to the merchants", ((string)(null)), table37, "Given ");
#line hidden
            global::Reqnroll.Table table38 = new global::Reqnroll.Table(new string[] {
                        "EstateName",
                        "MerchantName",
                        "ContractDescription"});
            table38.AddRow(new string[] {
                        "Test Estate 1",
                        "Test Merchant 1",
                        "Safaricom Contract"});
            table38.AddRow(new string[] {
                        "Test Estate 1",
                        "Test Merchant 1",
                        "Hospital 1 Contract"});
            table38.AddRow(new string[] {
                        "Test Estate 1",
                        "Test Merchant 1",
                        "PataPawa PostPay Contract"});
            table38.AddRow(new string[] {
                        "Test Estate 1",
                        "Test Merchant 1",
                        "PataPawa PrePay Contract"});
            table38.AddRow(new string[] {
                        "Test Estate 1",
                        "Test Merchant 2",
                        "Safaricom Contract"});
            table38.AddRow(new string[] {
                        "Test Estate 1",
                        "Test Merchant 2",
                        "Hospital 1 Contract"});
            table38.AddRow(new string[] {
                        "Test Estate 1",
                        "Test Merchant 2",
                        "PataPawa PostPay Contract"});
            table38.AddRow(new string[] {
                        "Test Estate 1",
                        "Test Merchant 2",
                        "PataPawa PrePay Contract"});
#line 82
 await testRunner.WhenAsync("I add the following contracts to the following merchants", ((string)(null)), table38, "When ");
#line hidden
            global::Reqnroll.Table table39 = new global::Reqnroll.Table(new string[] {
                        "EmailAddress",
                        "Password",
                        "GivenName",
                        "FamilyName",
                        "EstateName",
                        "MerchantName"});
            table39.AddRow(new string[] {
                        "user1",
                        "123456",
                        "TestMerchant",
                        "User1",
                        "Test Estate 1",
                        "Test Merchant 1"});
            table39.AddRow(new string[] {
                        "user2",
                        "123456",
                        "TestMerchant",
                        "User2",
                        "Test Estate 1",
                        "Test Merchant 2"});
#line 93
 await testRunner.GivenAsync("I have created the following security users", ((string)(null)), table39, "Given ");
#line hidden
#line 98
 await testRunner.GivenAsync("I have created a config for my device", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/LogoutLoginMerchantDetails.feature.ndjson", 3);
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Logout and relogin with a different merchant")]
        [global::NUnit.Framework.CategoryAttribute("PRTest")]
        public async global::System.Threading.Tasks.Task LogoutAndReloginWithADifferentMerchant()
        {
            string[] tagsOfScenario = new string[] {
                    "PRTest"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Logout and relogin with a different merchant", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 101
this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 4
await this.FeatureBackgroundAsync();
#line hidden
#line 102
 await testRunner.GivenAsync("I am on the Login Screen", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 103
 await testRunner.AndAsync("my device is registered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
 await testRunner.WhenAsync("I enter \'user1\' as the Email Address", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 105
 await testRunner.AndAsync("I enter \'123456\' as the Password", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
 await testRunner.AndAsync("I tap on Login", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 107
 await testRunner.ThenAsync("the Merchant Home Page is displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 108
 await testRunner.WhenAsync("I tap on Profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 109
 await testRunner.ThenAsync("the My Profile Page is displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 110
 await testRunner.WhenAsync("I tap on the Account Info button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 111
 await testRunner.ThenAsync("the Account Info Page is displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table40 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Balance",
                            "AvailableBalance"});
                table40.AddRow(new string[] {
                            "Test Merchant 1",
                            "0",
                            "0"});
#line 112
 await testRunner.AndAsync("the Account Info is displayed", ((string)(null)), table40, "And ");
#line hidden
#line 115
 await testRunner.WhenAsync("I click on the back button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 116
 await testRunner.ThenAsync("the My Profile Page is displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 117
 await testRunner.WhenAsync("I click on the back button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 118
 await testRunner.ThenAsync("the Merchant Home Page is displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 119
 await testRunner.WhenAsync("I tap on Logout", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 120
 await testRunner.ThenAsync("A message is displayed confirming I want to log out", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 121
 await testRunner.WhenAsync("I click yes", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 122
 await testRunner.ThenAsync("the Login Page is displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table41 = new global::Reqnroll.Table(new string[] {
                            "MerchantName",
                            "AddressLine1",
                            "AddressLine2",
                            "AddressLine3",
                            "AddressLine4",
                            "Town",
                            "Region",
                            "PostalCode",
                            "Country",
                            "ContactName",
                            "EmailAddress",
                            "EstateName"});
                table41.AddRow(new string[] {
                            "Test Merchant 2",
                            "test address line 1",
                            "test address line 2",
                            "test address line 3",
                            "test address line 4",
                            "TestTown",
                            "Test Region",
                            "TE57 1NG",
                            "United Kingdom",
                            "Test Contact 2",
                            "testcontact2@merchant2.co.uk",
                            "Test Estate 1"});
#line 123
 await testRunner.AndAsync("I replace the merchants with the following merchants", ((string)(null)), table41, "And ");
#line hidden
#line 126
 await testRunner.WhenAsync("I enter \'user2\' as the Email Address", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 127
 await testRunner.AndAsync("I enter \'123456\' as the Password", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 128
 await testRunner.AndAsync("I tap on Login", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 129
 await testRunner.ThenAsync("the Merchant Home Page is displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 130
 await testRunner.WhenAsync("I tap on Profile", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 131
 await testRunner.ThenAsync("the My Profile Page is displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 132
 await testRunner.WhenAsync("I tap on the Account Info button", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 133
 await testRunner.ThenAsync("the Account Info Page is displayed", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table42 = new global::Reqnroll.Table(new string[] {
                            "Name",
                            "Balance",
                            "AvailableBalance"});
                table42.AddRow(new string[] {
                            "Test Merchant 2",
                            "0",
                            "0"});
#line 134
 await testRunner.AndAsync("the Account Info is displayed", ((string)(null)), table42, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
