name: Release

on:
  release:
    types: [published]

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry  
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
jobs:
  release_android:
    runs-on: windows-2022
    name: "Android Release"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Setup Keystore File
        run: |
          echo "${{secrets.KEYSTORE_FILE }}" > transactionprocessing.keystore.asc
          gpg -d --passphrase "${{ secrets.KEYSTORE_PASSWORD_GPG }}" --batch transactionprocessing.keystore.asc > transactionprocessing.keystore
      
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}     
        shell: bash

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.100  
          
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources 

      - name: Restore Dependencies
        run: dotnet restore TransactionMobile.Maui.sln

      - name: Set Application Version
        uses: TransactionProcessing/actions@1.0.1
        with:
          filepath: 'TransactionMobile.Maui/TransactionMobile.Maui.csproj'
          versionnumber: ${{ steps.get_version.outputs.VERSION }}
          isWindows: false

      - name: Build Android
        run: dotnet publish TransactionMobile.Maui/TransactionMobile.Maui.csproj -c Release -f net7.0-android --no-restore /p:AndroidSigningKeyStore=transactionprocessing.keystore /p:AndroidSigningKeyPass="${{ secrets.KEYSTORE_PASSWORD }}" 
      
      - name: Upload Android Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-ci-build
          path: TransactionMobile.Maui/bin/Release/net7.0-android/com.transactionprocessing.pos-Signed.apk
          
      - name: Upload Artifact to App Center
        uses: Coxxs/AppCenter-Github-Action@v1
        with:
          appName: "Transaction-Processing/POS-Android"
          token: ${{secrets.APPCENTER_ANDROID_TOKEN}}
          group: Merchants
          file: TransactionMobile.Maui/bin/Release/net7.0-android/com.transactionprocessing.pos-Signed.apk
          notifyTesters: true
          debug: false  
          gitReleaseNotes: true

  release_windows:
    runs-on: windows-2022
    name: "Windows Release"
    env:
        ASPNETCORE_ENVIRONMENT: "Production"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
    
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}        
        shell: bash
       
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.100  
         
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore TransactionMobile.Maui.sln

      - name: Set Application Version
        uses: TransactionProcessing/actions@1.0.1
        with:
          filepath: 'TransactionMobile.Maui/TransactionMobile.Maui.csproj'
          versionnumber: ${{ steps.get_version.outputs.VERSION }}
          isWindows: true

      - name: Build Windows
        run: dotnet publish TransactionMobile.Maui/TransactionMobile.Maui.csproj -c Release -f net7.0-windows10.0.19041.0 --no-restore

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-ci-build
          path: TransactionMobile.Maui/bin/Release/net7.0-windows10.0.19041.0/win10-x64/AppPackages/TransactionMobile*/TransactionMobile*.msix
          
      - name: Upload Artifact to App Center
        uses: Coxxs/AppCenter-Github-Action@v1
        with:
          appName: "Transaction-Processing/POS-Windows"
          token: ${{secrets.APPCENTER_WINDOWS_TOKEN}}
          group: Merchants
          file: "TransactionMobile.Maui/bin/Release/net7.0-windows10.0.19041.0/win10-x64/AppPackages/TransactionMobile.Maui_${{ steps.get_version.outputs.VERSION }}.0_Test/TransactionMobile.Maui_${{ steps.get_version.outputs.VERSION }}.0_x64.msix"	
          notifyTesters: true
          debug: false  
          gitReleaseNotes: true          

  released-mac:
    runs-on: macos-11
    name: MacCatalyst Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3        

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}        
        
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.100  
          
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore TransactionMobile.Maui.sln

      - name: Set Application Version
        uses: TransactionProcessing/actions@1.0.1
        with:
          filepath: 'TransactionMobile.Maui/TransactionMobile.Maui.csproj'
          versionnumber: ${{ steps.get_version.outputs.VERSION }}
          isWindows: false

      - name: Build MacCatalyst
        run: dotnet publish TransactionMobile.Maui/TransactionMobile.Maui.csproj -c Release -f net7.0-maccatalyst --no-restore

      - name: Upload MacCatalyst Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-ci-build
          path: TransactionMobile.Maui/bin/Release/net7.0-maccatalyst/maccatalyst-x64/publish/*.pkg
              
  release-ios:
    runs-on: macos-11
    name: iOS Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}        
              
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.100  
                
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources
      
      - name: Restore Dependencies
        run: dotnet restore TransactionMobile.Maui.sln
      
      - name: Set Application Version
        uses: TransactionProcessing/actions@1.0.1
        with:
         filepath: 'TransactionMobile.Maui/TransactionMobile.Maui.csproj'
         versionnumber: ${{ steps.get_version.outputs.VERSION }}
         isWindows: false
      
      - name: Build iOS
        run: dotnet build TransactionMobile.Maui/TransactionMobile.Maui.csproj -c Release -f net7.0-ios --no-restore /p:buildForSimulator=True /p:packageApp=True /p:ArchiveOnBuild=False
      
      - name: Upload MacCatalyst Artifact
        uses: actions/upload-artifact@v3
        with:
          name: iOS-ci-build
          path: TransactionMobile.Maui/bin/Release/net7.0-ios/iossimulator-x64/**/*.app
