name: Build and Run iOS End To End Tests

on:
  pull_request:
    branches:
      - main

jobs:
  e2e_tests:
    runs-on: macos-14
    env:
      PLATFORM_VERSION: "17.2"
      DEVICE_NAME: "iPhone 15"
      APP_PATH: "./MyTestApp.app"

    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v4

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 🔧 Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: 📦 Install Appium + XCUITest driver
        run: |
          npm install -g appium
          appium driver install xcuitest

      - name: 🧹 Clean DerivedData and WDA cache
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ~/.appium/node_modules/appium-webdriveragent/Build

      - name: 🧪 Start Appium Server
        run: |
          nohup appium --log appium.log &

      - name: 📱 Create iOS Simulator (if needed)
        run: |
          SIMULATOR_NAME="ci-sim-$RANDOM"
          xcrun simctl create "$SIMULATOR_NAME" "$DEVICE_NAME" "com.apple.CoreSimulator.SimRuntime.iOS-${PLATFORM_VERSION//./-}"
          echo "SIMULATOR_NAME=$SIMULATOR_NAME" >> $GITHUB_ENV

      - name: 🚀 Boot simulator
        run: |
          xcrun simctl boot "$SIMULATOR_NAME"
          xcrun simctl list | grep Booted

      - name: Install MAUI Workloads
        run: |
          dotnet workload install ios --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources

      - name: Restore MAUI App for iOS
        run: dotnet restore TransactionMobile.Maui.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }} --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

      - name: Build Code
        run: dotnet build TransactionMobile.Maui/TransactionMobile.Maui.csproj  -f net9.0-ios -c Release --no-restore

      - name: Run iOS Navigation Tests
        run: dotnet test TransactionMobile.Maui.UiTests/TransactionMobile.Maui.UiTests.csproj --filter "(Category=iOSPRTest)&(Category=iOS)" --no-restore

      - name: Upload Appium Logs on Failure      
        if: failure()
        uses: actions/upload-artifact@v4
        with:
            name: ios-software_navigation_tests_appium
            path: appium.log

  