name: Build and Run iOS End To End Tests

on:
  pull_request:
    branches:
      - main

jobs:
  e2e_tests:
    runs-on: macos-15
    env:
      PLATFORM_VERSION: "17.2"
      DEVICE_NAME: "iPhone 15"
      APP_PATH: "./MyTestApp.app"

    steps:
      - name: 🧾 Checkout repo
        uses: actions/checkout@v4

      - name: Get IP
        run: ipconfig getifaddr en0

      - name: Cache Public IP
        run: echo "ENV_IPADDRESS=$(ipconfig getifaddr en0)" >> $GITHUB_ENV

      - name: Test IP
        run: echo $ENV_IPADDRESS

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 🔧 Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install colima and docker
        run: |
          brew install colima docker
          #brew install qemu
          wget https://github.com/abiosoft/colima-core/releases/download/v0.6.7/ubuntu-23.10-minimal-cloudimg-arm64.qcow2
          /opt/homebrew/bin/qemu-system-aarch64 -m 1G -drive file=ubuntu-23.10-minimal-cloudimg-arm64.qcow2,if=virtio -display default,show-cursor=on -machine type=virt -accel hvf -nographic &        
          #colima start --vm-type vz || colima start --vm-type qemu
          colima start
          docker ps
          docker pull alpine:latest
          docker image ls

      - name: Verify Docker Installation
        run: |
          docker version
          docker info

      - name: Pull images
        run: |
         docker pull stuartferguson/messagingservice:master
         docker pull stuartferguson/securityservice:master
         docker pull stuartferguson/transactionprocessor:master
         docker pull stuartferguson/transactionprocessoracl:master
         docker pull stuartferguson/testhosts:master
         docker pull stuartferguson/mobileconfiguration:master
         docker pull mcr.microsoft.com/azure-sql-edge
         docker pull eventstore/eventstore:21.10.0-buster-slim

      - name: 📦 Install Appium + XCUITest driver
        run: |
          npm install -g appium
          appium driver install xcuitest

      - name: 🧹 Clean DerivedData and WDA cache
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
          rm -rf ~/.appium/node_modules/appium-webdriveragent/Build

      - name: 🧪 Start Appium Server
        run: |
          nohup appium --log appium.log &

      - name: 📱 Create iOS Simulator (if needed)
        run: |
          SIMULATOR_NAME="ci-sim-$RANDOM"
          xcrun simctl create "$SIMULATOR_NAME" "$DEVICE_NAME" "com.apple.CoreSimulator.SimRuntime.iOS-${PLATFORM_VERSION//./-}"
          echo "SIMULATOR_NAME=$SIMULATOR_NAME" >> $GITHUB_ENV

      - name: 🚀 Boot simulator
        run: |
          xcrun simctl boot "$SIMULATOR_NAME"
          xcrun simctl list | grep Booted

      - name: Install MAUI Workloads
        run: |
          dotnet workload install ios --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources

      - name: Restore MAUI App for iOS
        run: dotnet restore TransactionMobile.Maui.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }} --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

      - name: Build Code
        run: dotnet build TransactionMobile.Maui/TransactionMobile.Maui.csproj  -f net8.0-ios -c Release --no-restore

      - name: Run iOS Navigation Tests
        run: dotnet test TransactionMobile.Maui.UiTests/TransactionMobile.Maui.UiTests.csproj --filter "(Category=PRTest)&(Category=iOS)" --no-restore

      - name: Upload Appium Logs on Failure      
        if: failure()
        uses: actions/upload-artifact@v4
        with:
            name: ios-software_navigation_tests_appium
            path: appium.log

      - name: Upload Colima stderr log if it exists
        if: failure()
        run: |
          if [ -f ~/.colima/_lima/colima/ha.stderr.log ]; then
            echo "::notice file=~/.colima/_lima/colima/ha.stderr.log::Uploading stderr log"
          else
            echo "No stderr log found." > colima-log-missing.txt
          fi
        shell: bash

      - name: Upload Colima logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
            name: colima-logs
            path: |
                ~/.colima/_lima/colima/ha.stderr.log
                colima-log-missing.txt
            if-no-files-found: warn

  