name: .NET MAUI UI Tests on Android Emulator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install Android SDK and Emulator
      id: android_sdk
      uses: android-actions/setup-android@v3
      with:
        api-level: '33'
        target: 'google_apis'
        arch: 'x86_64'
        distribution: 'system-images;android-33;google_apis;x86_64'
        add-system-image: 'system-images;android-33;google_apis;x86_64'

    - name: Verify Android SDK Installation
      run: |
        echo "Android SDK Location: ${{ steps.android_sdk.outputs.sdk-root }}"
        echo "Emulator Location: $(which emulator)"
        echo "adb version: $(adb version)"

    - name: Update SDK and Accept Licenses
      run: |
        sdkmanager --update --sdk_root=${ANDROID_HOME}
        echo "yes" | sdkmanager --licenses --sdk_root=${ANDROID_HOME}

    - name: Install System Image Explicitly
      run: |
        sdkmanager "system-images;android-33;google_apis;x86_64"

    - name: Debug List Installed Packages
      run: |
        echo "ANDROID_HOME: $ANDROID_HOME"
        sdkmanager --list_installed
 
    - name: Create and Start Android Emulator
      run: |
        sleep 30
        echo "no" | avdmanager create avd -n testAVD -k "system-images;android-33;google_apis;x86_64"
        "${{ steps.android_sdk.outputs.emulator-location }}" -avd testAVD -no-snapshot -no-window -noaudio -accel auto -no-boot-anim &
        adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'

    - name: Install .NET MAUI workload
      run: dotnet workload install maui

    - name: Install Appium and Drivers
      run: |
        sudo npm install -g appium
        appium driver install uiautomator2

    - name: Restore dependencies
      run: dotnet restore TransactionMobile.Maui/TransactionMobile.Maui.csproj
      working-directory: TransactionMobile.Maui

    - name: Build MAUI Application
      run: dotnet build TransactionMobile.Maui/TransactionMobile.Maui.csproj -c Release -f net8.0-android
      working-directory: TransactionMobile.Maui

    - name: Restore UI Test dependencies
      run: dotnet restore TransactionMobile.Maui.UiTests/TransactionMobile.Maui.UiTests.csproj
      working-directory: TransactionMobile.Maui.UiTests

    - name: Build UI Tests
      run: dotnet build TransactionMobile.Maui.UiTests/TransactionMobile.Maui.UiTests.csproj -c Release
      working-directory: TransactionMobile.Maui.UiTests

    - name: Run UI Tests
      run: dotnet test TransactionMobile.Maui.UiTests/TransactionMobile.Maui.UiTests.csproj -c Release --no-build
      working-directory: TransactionMobile.Maui.UiTests