name: .NET MAUI UI Tests on Android Emulator

on:
  pull_request:
    branches:
      - main

jobs:
  android-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK & Emulator
        run: |
          # Set up environment variables
          export ANDROID_SDK_ROOT=$HOME/android-sdk
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$PATH

          # Create necessary directories
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools

          # Download and install command-line tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
          unzip -q commandlinetools-linux-*.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          chmod +x $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager

          # Accept licenses and install required components
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "emulator" "platforms;android-33" "system-images;android-33;google_apis;x86_64"

          # Export paths for future steps
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$ANDROID_SDK_ROOT/emulator:$PATH" >> $GITHUB_ENV

      - name: Cache Emulator System Image
        uses: actions/cache@v3
        with:
          path: ~/.android/avd
          key: android-emulator-${{ runner.os }}-android-33

      - name: Create Android Emulator
        run: |
          echo "no" | avdmanager create avd -n test_emulator -k "system-images;android-33;google_apis;x86_64" --device "pixel_4"

      - name: Start Android Emulator (Optimized)
        run: |
          nohup emulator -avd test_emulator -no-window -gpu off -no-audio -no-boot-anim -snapshot save_snapshot > /dev/null 2>&1 &

      - name: Wait for Emulator to Boot (Timeout 5 min)
        run: |
          timeout 300 sh -c 'adb wait-for-device && while [[ "$(adb shell getprop sys.boot_completed)" != "1" ]]; do sleep 5; done'

      - name: Verify Emulator is Running
        run: adb devices
