name: Move PR Issues to Project Column

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  get-date:
    runs-on: ubuntu-latest
    outputs:
      project_name_prefix: ${{ steps.format_date.outputs.formatted_date }}
    steps:
      - name: Get PR creation date
        id: format_date
        run: |
          # Extract the month and year from the PR creation date
          PR_DATE="${{ github.event.pull_request.created_at }}"
          FORMATTED_DATE=$(date -d "$PR_DATE" "+%B %Y")  # Format to Month Year
          echo "formatted_date=${FORMATTED_DATE} Sprint" >> $GITHUB_ENV

  move-issues:
    needs: get-date
    uses: TransactionProcessing/org-ci-workflows/.github/workflows/move-linked-issue.yml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
      project_column_name: "In review"
      project_name_prefix: ${{ needs.get-date.outputs.project_name_prefix }}
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
