name: Build & Test Pull Requests

on:
  pull_request:
    branches: 
    - main

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry
  DOTNETVERSION:  6.0.200-preview.22055.15

jobs:
  # MAUI MacCatalyst Build
  build-ios:
    runs-on: macos-11
    name: MacCatalyst Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK ${{env.DOTNETVERSION}}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version:  '${{env.DOTNETVERSION}}'
          
      - name: Install .NET MAUI
        shell: bash
        run: |
          dotnet nuget locals all --clear 
          dotnet workload install maui --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json
          dotnet workload install android ios maccatalyst tvos macos maui wasm-tools --source https://aka.ms/dotnet6/nuget/index.json --source https://api.nuget.org/v3/index.json

      - name: Restore Dependencies
        run: dotnet restore TransactionMobile.Maui.sln
        
      - name: Build MacCatalyst App
        shell: bash
        run: |
          cd TransactionMobile.Maui
          dotnet build -f net6.0-ios -c Release -o ./artifacts
