name: Build & Test Pull Requests - Android

on:
  pull_request:
    branches: 
    - main


env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry 

jobs:
  build:
    runs-on: windows-latest
    name: Android Build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.100   

      - name: Install MAUI Workloads
        run: |
          dotnet workload install android --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources 

      - name: Restore Dependencies
        run: dotnet restore TransactionMobile.Maui.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }} --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

      - name: Build Code
        run: dotnet build TransactionMobile.Maui/TransactionMobile.Maui.csproj -c Release -f net7.0-android --no-restore

  unittest:
    needs: build
    runs-on: windows-latest
    name: Unit Tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Unit Tests
        run: dotnet test TransactionMobile.Maui.BusinessLogic.Tests/TransactionMobile.Maui.BusinessLogic.Tests.csproj    

  navigationtest:
    needs: build
    runs-on: windows-latest
    name: Navigation Tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Appium
        run: |
          npm install -g appium@next --unsafe-perm=true --allow-root
          appium driver install uiautomator2

      - name: Set up Android Emulator
        run: |
          mkdir android
          curl -o android/commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-win-6858069_latest.zip
          tar -xf android/commandlinetools.zip -C android/
          set ANDROID_SDK_ROOT=%RUNNER_WORKSPACE%\android\cmdline-tools
          echo "y" | %ANDROID_SDK_ROOT%\bin\sdkmanager --install "system-images;android-29;google_apis;x86"
          echo "no" | %ANDROID_SDK_ROOT%\bin\avdmanager --verbose create avd --force --name emulator --package "system-images;android-29;google_apis;x86" --abi "google_apis/x86" --device "pixel" --sdcard 512M
          emulator -avd emulator -no-audio -no-window -gpu swiftshader -no-boot-anim
          adb wait-for-device
          adb shell input keyevent 82

      - name: Run Android Navigation Tests
        run: |
          dotnet test TransactionMobile.Maui.UiTests/TransactionMobile.Maui.UiTests.csproj --filter (Category=PRNavTest)&(Category=Android)

  endtoendtest:
    needs: build
    runs-on: windows-latest
    name: End To End Tests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get IP
        run: ipconfig getifaddr en0

      - name: Cache Public IP
        run: echo "ENV_IPADDRESS=$(ipconfig getifaddr en0)" >> $GITHUB_ENV
        
      - name: Set up Appium
        run: |
          npm install -g appium@next --unsafe-perm=true --allow-root
          appium driver install uiautomator2

      - name: Set up Android Emulator
        run: |
          mkdir android
          curl -o android/commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-win-6858069_latest.zip
          tar -xf android/commandlinetools.zip -C android/
          set ANDROID_SDK_ROOT=%RUNNER_WORKSPACE%\android\cmdline-tools
          echo "y" | %ANDROID_SDK_ROOT%\bin\sdkmanager --install "system-images;android-29;google_apis;x86"
          echo "no" | %ANDROID_SDK_ROOT%\bin\avdmanager --verbose create avd --force --name emulator --package "system-images;android-29;google_apis;x86" --abi "google_apis/x86" --device "pixel" --sdcard 512M
          emulator -avd emulator -no-audio -no-window -gpu swiftshader -no-boot-anim
          adb wait-for-device
          adb shell input keyevent 82

      - name: Run Android End To End Tests
        run: |
          dotnet test TransactionMobile.Maui.UiTests/TransactionMobile.Maui.UiTests.csproj --filter (Category=PRTest)&(Category=Android)
