name: Build & Test Pull Requests

on:
  pull_request:
    branches: 
    - main

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  # MAUI Android Build
  build-android:
    runs-on: self-hosted
    name: Android Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #- name: Setup .NET 6
      #  uses: actions/setup-dotnet@v1
      #  with:
      #    dotnet-version: 6.0.200-preview.22055.15
      #    include-prerelease: true
          
      #- uses: actions/setup-java@v2
      #  with:
      #    distribution: 'microsoft'
      #    java-version: '11'

      #- name: Install MAUI Workloads
      #  run: |
      #    dotnet workload install android --ignore-failed-sources
      #    dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore TransactionMobile.Maui.sln

      - name: Build Code
        run: dotnet build TransactionMobile.Maui/TransactionMobile.Maui.csproj -c Release -f net6.0-android

      - name: Run Unit Tests
        run: dotnet test TransactionMobile.Maui.BusinessLogic.Tests/TransactionMobile.Maui.BusinessLogic.Tests.csproj

      #- name: Upload Android Artifact
      #  uses: actions/upload-artifact@v2.3.1
      #  with:
      #    name: android-ci-build
      #    path: src/MauiBeach/bin/Release/net6.0-android/*Signed.a*
