name: Build & Test Pull Requests

on:
  pull_request:
    branches: 
    - main

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  build-windows:
    runs-on: self-hosted
    name: Windows Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      #- name: Setup .NET 6
      #  uses: actions/setup-dotnet@v1
      #  with:
      #    dotnet-version: 6.0.200-preview.22055.15
      #    include-prerelease: true

      #- name: Setup MSBuild
      #  uses: microsoft/setup-msbuild@v1.1
      #  with:
      #    vs-prerelease: true

      #- name: Install MAUI Workloads
      #  run: |
      #    dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore TransactionMobile.Maui.sln --source https://api.nuget.org/v3/index.json --source https://www.myget.org/F/transactionprocessing/api/v3/index.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

      - name: Build Code
        run: msbuild TransactionMobile.Maui.sln  -restore -p:Configuration=Release  -p:TargetFramework=net6.0-windows10.0.19041  /p:RestoreSources=https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json 

      - name: Run Unit Tests
        run: dotnet test TransactionMobile.Maui.Tests/TransactionMobile.Maui.Tests.csproj

  #    #- name: Upload Windows Artifact
  #    #  uses: actions/upload-artifact@v2.3.1
  #    #  with:
  #    #    name: windows-ci-build
  #    #    path: src/MauiBeach/bin/Release/net6.0-windows*/**/MauiBeach*.msix
