name: Build & Test Pull Requests - Android

on:
  pull_request:
    branches: 
    - main

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry  

jobs:
  # MAUI Android Build
  build-android:
    #runs-on: windows-2022
    runs-on: macos-12
    name: Android Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get IP
        run: ipconfig getifaddr en0

      - name: Cache Public IP
        run: echo "ENV_IPADDRESS=$(ipconfig getifaddr en0)" >> $GITHUB_ENV

      - name: Test IP
        run: echo $ENV_IPADDRESS
          
      - name: Setup Docker
        run: |
         brew install docker
         colima start --cpu 2 --memory 8 --disk 100

      #- name: Pull images
      #  run: |
      #   docker pull stuartferguson/messagingservice:master
      #   docker pull stuartferguson/estatemanagement:master
      #   docker pull stuartferguson/securityservice:master
      #   docker pull stuartferguson/transactionprocessor:master
      #   docker pull stuartferguson/transactionprocessoracl:master
      #   docker pull stuartferguson/testhosts:master
      #   docker pull stuartferguson/vouchermanagementacl:master
      #   docker pull stuartferguson/fileprocessor:master
      #   docker pull stuartferguson/callbackhandler:master
      #   docker pull stuartferguson/mobileconfiguration:master
      #   docker pull stuartferguson/mobileconfiguration:master
      #   docker pull stuartferguson/mobileconfiguration:master
      #   docker pull mcr.microsoft.com/azure-sql-edge
      #   docker pull eventstore/eventstore:21.10.0-buster-slim

      - uses: malinskiy/action-android/install-sdk@release/0.1.1
      - run: sdkmanager "platform-tools" "platforms;android-33"
      - run: sdkmanager "build-tools;30.0.2"
      - run: adb devices

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.12.0'

      - name: Set up Appium
        run: |
          npm install -g appium --unsafe-perm=true --allow-root

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.100            
          
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Install MAUI Workloads
        run: |
          dotnet workload install android --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources 

      - name: Restore Dependencies
        run: dotnet restore TransactionMobile.Maui.sln --source https://api.nuget.org/v3/index.json --source https://www.myget.org/F/transactionprocessing/api/v3/index.json --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

      - name: Build Code
        run: dotnet build TransactionMobile.Maui/TransactionMobile.Maui.csproj -c Release -f net7.0-android --no-restore

      #- name: Run Unit Tests
      #  run: dotnet test TransactionMobile.Maui.BusinessLogic.Tests/TransactionMobile.Maui.BusinessLogic.Tests.csproj
        
      - name: Run Integration Tests - Android
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.4
        with:
          cmd: dotnet test TransactionMobile.Maui.UiTests/TransactionMobile.Maui.UiTests.csproj --filter (Category=PRTest)&(Category=Android)
          api: 28
          tag: default
          abi: x86   
          verbose: true

      #- name: Upload Android Artifact
      #  uses: actions/upload-artifact@v2.3.1
      #  with:
      #    name: android-ci-build
      #    path: src/MauiBeach/bin/Release/net6.0-android/*Signed.a*

      #- uses: actions/upload-artifact@v2
      #  if: ${{ failure() }}
      #  with:
      #    name: tracelogsios
      #    path: /Users/runner/txnproc/trace/

      - name: Save logcat output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: logcat
          path: artifacts/logcat.log 
