name: Build & Test Pull Requests - Android

on:
  pull_request:
    branches: 
    - main

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry  

jobs:
  build-android-unit-tests :
    runs-on: macos-12
    name: Android Build - Unit Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Install MAUI Workloads
        run: |
          dotnet workload install android --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources 

      - name: Restore Dependencies
        run: dotnet restore TransactionMobile.Maui.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }} --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

      - name: Build Code
        run: dotnet build TransactionMobile.Maui/TransactionMobile.Maui.csproj -c Release -f net7.0-android --no-restore

      - name: Run Unit Tests
        run: dotnet test TransactionMobile.Maui.BusinessLogic.Tests/TransactionMobile.Maui.BusinessLogic.Tests.csproj              
        
  build-android-nondocker:
    runs-on: macos-12
    name: Android Build - Navigation Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
          
      - name: Setup Docker
        run: |
         brew install docker
         colima start --cpu 2 --memory 8 --disk 100

      - uses: malinskiy/action-android/install-sdk@release/0.1.1
      - run: sdkmanager "platform-tools" "platforms;android-33"
      - run: sdkmanager "build-tools;30.0.2"
      - run: adb devices

      - name: Set up Appium
        run: |
          npm install -g appium@next --unsafe-perm=true --allow-root
          appium driver install uiautomator2
          
      - name: Install MAUI Workloads
        run: |
          dotnet workload install android --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources 

      - name: Restore Dependencies
        run: dotnet restore TransactionMobile.Maui.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }} --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

      - name: Build Code
        run: dotnet build TransactionMobile.Maui/TransactionMobile.Maui.csproj -c Release -f net7.0-android --no-restore        
        
      - name: Run Navigation Integration Tests - Android
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.4
        with:
          cmd: dotnet test TransactionMobile.Maui.UiTests/TransactionMobile.Maui.UiTests.csproj --filter (Category=PRNavTest)&(Category=Android)
          api: 29
          tag: default
          abi: x86   
          verbose: false
          cmdOptions: >
            -no-window
            -gpu swiftshader_indirect
            -no-snapshot
            -noaudio
            -no-boot-anim
            -camera-back none
            -camera-front none        
                  
      - name: Save logcat output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: logcat
          path: artifacts/logcat.log 

  build-android-withdocker:
    runs-on: macos-12
    name: Android Build - End To End Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get IP
        run: ipconfig getifaddr en0

      - name: Cache Public IP
        run: echo "ENV_IPADDRESS=$(ipconfig getifaddr en0)" >> $GITHUB_ENV
          
      - name: Setup Docker
        run: |
         brew install docker
         colima start --cpu 2 --memory 8 --disk 100

      - name: Pull images
        run: |
         docker pull stuartferguson/messagingservice:master
         docker pull stuartferguson/estatemanagement:master
         docker pull stuartferguson/securityservice:master
         docker pull stuartferguson/transactionprocessor:master
         docker pull stuartferguson/transactionprocessoracl:master
         docker pull stuartferguson/testhosts:master
         docker pull stuartferguson/mobileconfiguration:master
         docker pull mcr.microsoft.com/azure-sql-edge
         docker pull eventstore/eventstore:21.10.0-buster-slim

      - uses: malinskiy/action-android/install-sdk@release/0.1.1
      - run: sdkmanager "platform-tools" "platforms;android-33"
      - run: sdkmanager "build-tools;30.0.2"
      - run: adb devices

      - name: Set up Appium
        run: |
          npm install -g appium@next --unsafe-perm=true --allow-root
          appium driver install uiautomator2
          
      - name: Install MAUI Workloads
        run: |
          dotnet workload install android --ignore-failed-sources
          dotnet workload install maui --ignore-failed-sources 

      - name: Restore Dependencies
        run: dotnet restore TransactionMobile.Maui.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }} --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

      - name: Build Code
        run: dotnet build TransactionMobile.Maui/TransactionMobile.Maui.csproj -c Release -f net7.0-android --no-restore

      - name: Run Integration Tests - Android
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.4
        with:
          cmd: dotnet test TransactionMobile.Maui.UiTests/TransactionMobile.Maui.UiTests.csproj --filter (Category=PRTest)&(Category=Android)
          api: 29
          tag: default
          abi: x86   
          verbose: false
          cmdOptions: >
            -no-window
            -gpu swiftshader_indirect
            -no-snapshot
            -noaudio
            -no-boot-anim
            -camera-back none
            -camera-front none        

      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: tracelogsandroid
          path: /Users/runner/txnproc/trace/

      - name: Save logcat output
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: logcat
          path: artifacts/logcat.log 
