name: Build and Run Windows Navigation Tests

on:
  pull_request:
    branches:
      - main

jobs:
  software_navigation_tests:
    runs-on: windows-2022
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-prerelease: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '9.0.x'
     
      - name: Install MAUI workloads
        run: |
          dotnet workload install maui

      - name: Install Appium and Drivers
        run: |
          npm install -g appium --unsafe-perm=true --allow-root
          appium driver install --source=npm appium-windows-driver

      - name: Start Appium Server
        run: |
          nohup appium --log appium.log &

      - name: Restore MAUI App for Windows
        run: dotnet restore TransactionMobile.Maui.sln --source ${{ secrets.PUBLICFEEDURL }} --source ${{ secrets.PRIVATEFEED_URL }} --source https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json

      - name: Build Code
        run: dotnet build TransactionMobile.Maui/TransactionMobile.Maui.csproj  -f net9.0-windows10.0.19041.0 -c Release --no-restore -r win-x64

      - name: Decrypt PFX File
        run: |
          echo "${{ secrets.WINDOWSSIGNINGCERT }}" > cert.pfx.asc
          certutil -decode cert.pfx.asc cert.pfx

      - name: Add Cert to Store
        run: certutil -user -q -p ${{ secrets.WINDOWSSIGNINGCERTPWD }} -importpfx cert.pfx NoRoot

      - name: Publish App
        run: |
         dotnet publish TransactionMobile.Maui/TransactionMobile.Maui.csproj -c Release -f net9.0-windows10.0.19041.0 -r win-x64 /p:UseMonoRuntime=false /p:WindowsAppSDKSelfContained=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateThumbprint="${{ secrets.WINDOWSSIGNINGCERTTHUMBPRINT }}"      
      
      - name: Install App
        shell: powershell
        run: |         
         Import-Module Appx 
         .\TransactionMobile.Maui/bin/Release/net9.0-windows10.0.19041.0/win-x64/AppPackages/TransactionMobile.Maui_1.0.0.0_Test/Install.ps1 -Force

      - name: Get installed AppId
        id: get_appid
        run: |
           $pkg = Get-AppxPackage -Name TransactionMobile
           $appId = "$($pkg.PackageFamilyName)!App"
           Write-Output "AppId=$appId"
           echo "APPID=$appId" >> $env:GITHUB_ENV
        shell: powershell

      - name: Use AppId in Appium/WinAppDriver step
        run: |
            echo "AppId is $env:APPID"
            # You can now pass $env:APPID to test scripts or config
        shell: powershell

      - name: Run Windows Navigation Tests
        run: dotnet test TransactionMobile.Maui.UiTests/TransactionMobile.Maui.UiTests.csproj --filter "(Category=PRNavTest)&(Category=Windows)" --no-restore

      - name: Upload Appium Logs on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
            name: windows-software_navigation_tests_appium
            path: appium.log

  